import type { NextPage } from 'next'
import Head from 'next/head'
import TaskList from '../components/TaskList'

const Home: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <TaskList />
        </main>
      </div>
    )
}

export default Home
